// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnN6zafeGWDtzuW10QeZR5lX2pyXCjKnY',
    appId: '1:284662378009:web:0eef4724c9dc887e178488',
    messagingSenderId: '284662378009',
    projectId: 'basket-7d10f',
    authDomain: 'basket-7d10f.firebaseapp.com',
    databaseURL: 'https://basket-7d10f-default-rtdb.firebaseio.com',
    storageBucket: 'basket-7d10f.appspot.com',
    measurementId: 'G-FCVFBJ7D1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZRJlPyyLfu1BBOrng0T0UAWCR4GtXQg',
    appId: '1:284662378009:android:3475626de79c10f1178488',
    messagingSenderId: '284662378009',
    projectId: 'basket-7d10f',
    databaseURL: 'https://basket-7d10f-default-rtdb.firebaseio.com',
    storageBucket: 'basket-7d10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnptxobyAhqEWPBsolirdnmVbYb0ff-U',
    appId: '1:284662378009:ios:66231fb09f42166d178488',
    messagingSenderId: '284662378009',
    projectId: 'basket-7d10f',
    databaseURL: 'https://basket-7d10f-default-rtdb.firebaseio.com',
    storageBucket: 'basket-7d10f.appspot.com',
    iosClientId: '284662378009-h5gtqpnq9pq14q6ltlp1f0sain9fjcu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.basket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQnptxobyAhqEWPBsolirdnmVbYb0ff-U',
    appId: '1:284662378009:ios:035162c6b7e2f32d178488',
    messagingSenderId: '284662378009',
    projectId: 'basket-7d10f',
    databaseURL: 'https://basket-7d10f-default-rtdb.firebaseio.com',
    storageBucket: 'basket-7d10f.appspot.com',
    iosClientId: '284662378009-806ikbnj0h4mmoq4b139seq77lt1mcem.apps.googleusercontent.com',
    iosBundleId: 'com.example.basket.RunnerTests',
  );
}
